### ISSUE TITLE
Tink worker should never exit

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/tink#463] opened 2021-03-17 19:59 UTC
Tink worker should pass on any errors back to tink server but remain up. Otherwise the machine needs to be rebooted in order to get tink worker back up and running and ready to process more workflows. This seems unnecessary just to deal with an error, imagine if `init` did the same ;).

## Expected Behaviour

Tink worker reports back errors but continues to stay up and connected to tink server.

## Current Behaviour

Tink worker exits and we need to reboot or log in and restart tink-worker to get into a workflow processing state again.

**Comment by gianarb** [comment] 2021-03-18 14:47
This is a duplicate of this https://github.com/tinkerbell/tink/issues/458#issuecomment-799423084 but it is written in a better form! So I will close the old one in favor of this!

**Comment by jacobweinstock** [comment] 2022-12-23 02:00
Tink worker should be in a better position with https://github.com/tinkerbell/tink/pull/655, i believe there is still lots of room for improvement though and we have a roadmap item to refactor tink-worker entirely. With that said, I will close this issue and we can revisit upon request.

**Closed** 2022-12-23 20:33 UTC
Labels: kind/feature, priority/important-longterm
