### ISSUE TITLE
tink-worker container should keep on running and seeking for workflow tasks to execute 

### ISSUE THREAD

**Issue by parauliya** [tinkerbell/tink#222] opened 2020-07-20 06:38 UTC
tink-worker container should keep on running even after the completion of all the current workflows. 

## Expected Behaviour
tink-worker container should not exit if all the workflows executed successfully.
 
## Current Behaviour
Currently tink-worker container exits once all the workflows provided to it are completed successfully.

## Possible Solution
1. Use `gRPC stream`  instead of  `sleep` for polling workflow.
2. The infinite loop inside the worker container should keep on running irrespective of worklfows state or completion.
     ( using `sleep` for polling over it ).

## Context
Right now there worker exits after the execution of workflows. So if there is a new workflow for the same worker it need to be rebooted.
Right now there is a sleep in worker container between asking for a workflow. This leads to a lot of unnecessary logs which crashes the terminal or overflowing the RAM/disks etc.
This also covers the remaining part of #196 once it is fixed.

**Comment by Cbkhare** [comment] 2020-07-20 06:54
this issue seems to be duplicate of https://github.com/tinkerbell/tink/issues/72

**Comment by parauliya** [comment] 2020-07-20 07:36
> this issue seems to be duplicate of #72

Not exactly duplicate but yes it contains the same so we can close the previous one which is #72 .

**Closed** 2020-08-04 12:18 UTC
Labels: enhancement
