### ISSUE TITLE
Updating a template does not update the workflows associated with that template

### ISSUE THREAD

**Issue by detiber** [tinkerbell/tink#292] opened 2020-09-15 16:14 UTC
## Expected Behaviour
Updating a template should update existing workflows associated with that template

## Current Behaviour
Updating a template does not affect existing workflows associated with that template

## Steps to Reproduce (for bugs)
1. Create an empty template (can be accomplished by https://github.com/tinkerbell/tink/issues/291)
2. Create a workflow associated with the previously created template
3. Attempt to boot hardware that is associated with the workflow created above
4. When the expected jobs fail to run, update the template to a proper template
5. Reboot the hardware that is associated with the workflow, and it will fail to run jobs again.

## Context
I mistakenly created an empty template by specifying the wrong file name and since it completed successfully, I created a workflow based on the empty template. I then attempted to boot hardware into the workflow and was confused as to why the configured jobs had failed to run. Once I realized the error, I attempted to update the template and expected that to affect the workflow that had not yet been run.

**Comment by gianarb** [comment] 2020-09-16 14:00
I have a couple of questions because I think I am reading this lifecycle in a different way: 

In which state is the workflow at the end of point (4)? Is it in a failed state? And how do you know that?

**Comment by mmlb** [comment] 2020-10-13 17:49
Closing as not a bug. This is a missing docs bug and I've opened up tinkerbell/tinkerbell-docs#21 to address there.

**Closed by mmlb** 2020-10-13 17:49 UTC
