### ISSUE TITLE
where can I find sample action-images?

### ISSUE THREAD

**Issue by rafiqkattangere** [tinkerbell/tink#119] opened 2020-05-18 01:15 UTC
I see you guys refer to some action-images in your samples. Sounds like there might be some place where I can see how to write one?

**Comment by alexellis** [comment] 2020-05-18 10:57
Hi @rafiqkattangere, would you say that this is a duplicate of #91?

**Comment by nshalman** [comment] 2021-06-29 15:28
Examples now live in https://github.com/tinkerbell/hub/tree/main/actions

Thanks for reporting!

**Closed by nshalman** 2021-06-29 15:28 UTC
Labels: P3, documentation
