### ISSUE TITLE
tink-cli does not error on unknown arguments

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/tink#376] opened 2020-12-04 23:07 UTC
I just ran `tink-cli template create -name manny...` and could not find my template in the `list` output. After lots of confusion I finally noticed one named `ame` and :boom: I figured it out.

## Expected Behaviour

tink-cli should have complained about the unused `manny` argument and exited with an error.

**Comment by gianarb** [comment] 2020-12-10 14:25
I can't reproduce this issue:

```
$ go run cmd/tink-cli/main.go --awergsergsregsrtg
Error: unknown flag: --awergsergsregsrtg
Usage:
  tink [command]

Available Commands:
  hardware    tink hardware client
  help        Help about any command
  template    tink template client
  workflow    tink workflow client

Flags:
  -f, --facility string   used to build grpc and http urls
  -h, --help              help for tink
  -v, --version           version for tink

Use "tink [command] --help" for more information about a command.

unknown flag: --awergsergsregsrtg
exit status 1
```

It appears to recognize unknown flags
```
unknown flag: --awergsergsregsrtg
```
I saw there are more specific issues about flags, for now I am closing this one

**Closed by gianarb** 2020-12-10 14:25 UTC
Labels: P1, bug
